### ISSUE TITLE
Corrupción en el sistema de Supervisión del Censo

### ISSUE THREAD

**Issue by Byza** [JavierGonzalez/VirtualPol#119]
Desgraciadamente, el sistema de supervision del censo es insostenible.

Unos años atrás, la asamblea 15M aumentó su actividad, con ello el número de votos de confianza a ciudadanos de confianza (relativa confianza) y un año despúes, algunos se "presentaron" a SC.
El sistema encontró su primer fallo. Estos ciudadanos no eran veteranos y no estaban acostumbrados a expulsiones y TOS. Hubo expulsiones improcedentes y omisiones de expulsiones más que validas. Los SC de simuladores nos encargamos (1era del plural) de arreglarlo.
Poco después, estos SC de asambleas dejaron de ser activos.

Llegamos entonces al segundo fallo del sistema. Los ciudadanos elegidos como SC en 15M dejaron de ser activos. Y continuaron siendo SC. Algunos eran activos, pero no como supervisores. 
Los SC de POL y simuladores nos quedamos solos. Necesitabamos sus votos en las decisiones, pero no acudían. Baldor, Sanchez, Asier o Alsirio quedaros con el panel y el doble de "trabajo".

Pero hubo una rencilla en 15M y se escindieron hacia el movimiento R25S, que dió nuevos usuarios "top confianza". 
Ojalá ellos se hubiesen vuelto inactivos.

Llegó el tercer problema del sistema de SC, la "corrupción". Estos usuarios comenzaron a buscar la expulsión de aquellos que eran sus rivales en 15M. Surgió el caso Eldany (reiterado y aún actual), por el cual los SC de 25RS querían expulsar a Eldany por "agraviar" a su plataforma. El TOS, obviamente, no contiene punto que trate ese tema.

Y llegó el tercer punto, literal b (3.b) que destruyó el sistema de SC. 
Los votos de confianza en contra (el votar negativo a tus "enemigos") en los simuladores siempre fué el gran error.
Pero esa misma táctica se usó de forma deliberada en los SC tradicionales de los Simuladores, Baldor, Kvothe, Sanchez, Alsirio... fueron "relegados" de sus funciones por un aluvión de votos negativos. 
No acusaré a nadie. Pero la reducción fué tras el Caso Eldany, de +20 a -10.

El sistema de SC se rompió.

Las consecuencias las vivimos hoy, las expulsiones no se estan realizando.
Algunos ciudadanos marchan para no volver,
Otros estan siendo obligados a marchar.

S.O.S.

**Comment by Kronossf** [comment]
Caramba, ese expulsado injustamente resulta que fuí yo, sin posibilidad de defensa ni ninguna otra garantía democrática... justamente estaba resolviendo este tema através de la supervisión y su papel intrínseco al resto de cargos y la responsabilidad en sí misma... pero vaya por dónde, pasó justo lo que pasa siempre:colapso.

Ya lo digo ahora de nuevo: el sistema debe ser orgánico en una parte importante, no todo es la programación y sus estructuras inertes, los argumentos y la excelencia prima! 

"Unos años atrás, la asamblea 15M aumentó su actividad, con ello el número de votos de confianza a ciudadanos de confianza (relativa confianza) y un año despúes, algunos se "presentaron" a SC.
El sistema encontró su primer fallo. Estos ciudadanos no eran veteranos y no estaban acostumbrados a expulsiones y TOS. Hubo expulsiones improcedentes y omisiones de expulsiones más que validas. Los SC de simuladores nos encargamos (1era del plural) de arreglarlo.
Poco después, estos SC de asambleas dejaron de ser activos."

**Comment by Shrewd** [comment]
Se corrige un fallo para el sistema de supervision del censo.

Link : https://github.com/JavierGonzalez/VirtualPol/commit/afd568c5dd1884f32d19621162ab3323b7bf47d8
