### ISSUE TITLE
Fallo total en cuenta Gobierno de Arcadia

### ISSUE THREAD

**Issue by Baldor9** [JavierGonzalez/VirtualPol#121]
Lo normal es que la cuenta gobierno sea http://mic.virtualpol.com/pols/cuentas/1/
En este mpmento el número de esa cuenta es http://mic.virtualpol.com/pols/cuentas/558/

Lo que hace que se cree dinero del aire y se destruyan los impuestos.

**Comment by Shrewd** [comment]
Issue Antiguo

Por el momento la economía es correcta
http://simulador.virtualpol.com/info/economia
