### ISSUE TITLE
IRREGULARIDADES EN VIRTUALPOL?

### ISSUE THREAD

**Issue by Coke25S** [JavierGonzalez/VirtualPol#126]
Hola GONZO 

¿Te has enterado de lo que han hecho y como esa gente que tienes en VirtualPol con tanta confianza? Esos llamados Supervisores del Censo que parece ser que no reconocen las medidas que las plataformas aprobamos por medio de Referendums democraticos, para intentar apartar a todo aquel que hace daño a nuestro trabajo... bien, pues esos tan respetuosos Supervisores de Censo se nos han cargado a Santig, Dani y a mi mismo (Koke25S) . . . O deshaces este entuerto tu mismo, o me temo que VirtualPol ha muerto y sera un simple simulador infectado de gente que pretende quedarse con todo virtualpol para ellos solos. . . y mira que te avisamos que el TOS esta incompleto y no protege ni a las plataformas ni da poder a los coordinadores.  En tus manos queda hacer algo al respecto. Ya van dos en un mes de estas, resulta que ellos pueden destrozar nuestro trabajo con la impunidad de ese incompleto TOS, pero nosotros no podemos aplicar segun ellos las medidas que aprobadas bajo un referendum democratico aplicamos a los indeseables en la plataforma. . . ¿Doble rasero? ¿Somos los de las plataformas exclavos de los simuladores?, como entiendes tu esto?. 

Saludos.

**Comment by Coke25S** [comment]
Este es un comunicado de @Dani sobre su expulsión junto con @santig y @Koke25s

Dani escribió:

Primero agradecer al compañero @pepeolobo por haceros llegar estas líneas a toda la Asamblea. Yo no puedo hacerlo por estar expulsado de VP por defender a esta Asamblea.
La expulsión está basada en esto:
3. Ataques a la comunidad:
d. El uso reiterado o sistemático de “kicks” superiores a 15 minutos sin cobertura legal dentro de la plataforma.
(ver TOS)

Bien, como estos iluminados de SC no dan más de sí, les explicaré algo que creo importante.
El TOS, como se puede ver, tiene tres puntos que, a su vez, tienen varios sub-puntos.
Si miran en cualquier diccionario el prefijo “sub”, este es su significado:
1. pref. Significa 'bajo' o 'debajo de'.
2. pref. Indica inferioridad, subordinación, acción secundaria.

Pues bien estos, utilizan el sub-punto 3.d para apoyarse en la expulsión. Teniendo en cuenta el significado del prefijo, la expulsión es injusta, ya que con mi actuación he defendido la comunidad. Es decir, el punto, lo superior.
Siguiendo con el susodicho sub-punto. Dice claramente reiterado o sistemático; vayamos al significado de reiterado (a recordar que viene del verbo reiterar).
Reiterar: Volver a decir o hacer algo.
Está claro que no he podido cometer una reiteración porque solo los he kickeado una vez. Con lo cual la expulsión es ilegal porque no he incumplido el TOS.

Pero una vuelta más.
“El borrado de documentos no es ilegal porque no lo pone el TOS”. Bien, aquí pondré un ejemplo, espero que sus mentes brillantes lo entiendan.
A) Animales:
1. Gato.
2. Jabalí.
3. Caracol.

Si alguien viene y escribe “perro”, está bien o mal. ¿Está mal porque no aparece en la lista? ¿O está bien porque pertenece al punto principal, en este caso, animales?
Pues es lo que no entienden los SC: ATAQUES A LA COMUNIDAD. ¿Qué parte de “ataques a la comunidad” no se entiende?
Recordarles que AV no es un simulador y por lo tanto no tiene las mismas normas que estos.

Como bien dice @pepeolobo, abrí un hilo y los Coordinadores me dieron su apoyo. Se lanzó un referéndum y se decidió apoyar mi actuación. Creo que es buen momento para recordar lo que dijo @GONZO hace unos días en el chat de AV.
“cada plataforma es independiente y deberá lidiar con sus usuarios como quiera”
“es decir, sois libres y debéis defender vuestro espacio virtual”
Lo que da a entender que, la actuación de esta Asamblea es totalmente legítima. La expulsión no tiene base dado que AV, en un referéndum, ha decidido que los dos implicados en el ataque sean kickeados cada vez que se presenten por la Asamblea. En definitiva, la Asamblea se ha defendido.

Si tuve que llegar a ese extremo es porque los SC no cumplieron el TOS en su punto 3: Ataques a la comunidad.

Perdonad si es un ladrillo, saludos.
Dani

**Comment by Coke25S** [comment]
Otra lindeza de la gente de tu confianza . . . 


10:37  Shrewd: Alguien puede decirle al inutil de coke que para hablar con gonzo no escriba en el github?

Esto es el proyecto VirtualPol del futuro?. FELICIDADES.

**Comment by Coke25S** [comment]
![image](https://cloud.githubusercontent.com/assets/14910922/10694494/c01342ea-799e-11e5-8d7b-accf57d06202.png)

**Comment by Coke25S** [comment]
![image](https://cloud.githubusercontent.com/assets/14910922/10694506/d38c4e52-799e-11e5-887e-24b65549184d.png)

**Comment by Coke25S** [comment]
Pruebas claras de que Lord_Bastian, cuando era todavia un "anonimo" en twiter por que no se le conocia como tal alli, amenazaba a Santig, con lo cual segun el TOS este tio debe ser expulsado.

**Comment by JavierGonzalez** [comment]
He derogado el punto 3.d del TOS.
